### ISSUE TITLE
Decision tree

### ISSUE THREAD

**Issue by JOHNKYON** [JOHNKYON/Sora#3]
Building a decision tree visualization module.

This should include *visualization tool* and *simple demo* for presenting.

### Subtasks
- [x] Build model demos (For test and presentation) #4 
- [x] Build unit test #5
- [x] Build visualization tool: #6

**Comment by ZhuGongpu** [comment]
Should be divided into a couple of atomic subtasks. @JOHNKYON

**Comment by JOHNKYON** [comment]
Agreed.
Close the issue and create a new one.

**Comment by ZhuGongpu** [comment]
Re https://github.com/JOHNKYON/Sora/issues/3#issuecomment-387084847:

Listing all the subtasks in the [description section](https://github.com/JOHNKYON/Sora/issues/3#issue-320827601) will do.

**Comment by JOHNKYON** [comment]
Re https://github.com/JOHNKYON/Sora/issues/3#issuecomment-387085487

How does the [description section](https://github.com/JOHNKYON/Sora/issues/3#issue-320827601) look like now?

**Comment by ZhuGongpu** [comment]
**TERRIBLE**!

<img width="354" alt="image" src="https://user-images.githubusercontent.com/7722194/39709312-22612cea-524c-11e8-88e1-640a51a4b18b.png">

Ref https://help.github.com/articles/about-task-lists/#creating-tas… .
